title: Kaduri's blog
email: kaduriomri@gmail.com
description: Document my path to understand cool things in AI
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://omrikaduri.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  OmriKaduri
domain: omrikaduri.github.io
# Build settings
markdown: kramdown
twitter_username: omri_kaduri
highlighter: rouge

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-archives

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
- Gemfile
- Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3

